### ISSUE TITLE
feature request : support for symbol with space in attribute

### ISSUE THREAD

**Issue by avilleret** [CICM/CicmWrapper#10]
I would like to be able to enter symbol with space as attribute.

I was thinking about using the double quotes " to delimit a symbol with space.

In that way, we could use something like : 
`[c.patcherargs bla @myAttr "foo bar" tre @anotherAttr 3.2]`
And the attribute `myAttr` will be a list of 2 atoms : "foo bar" (which is one symbol with space) and tre.

Do you think it's possible to parse box argument to do something like that ?

I've already done something similar to use symbol with space with a custom setter message (see https://github.com/jamoma/JamomaPureData/blob/dev/library/source/JamomaModularForPd.cpp#L1114-L1144).
But doing the same with in-box attribute needs some changes in wrapper I guess.

**Comment by pierreguillot** [comment]
You can already fo that with simple quotes '. I don't know why I use simple quotes there must be a reason... I guess. I'll have a look at it.

**Comment by avilleret** [comment]
good to know but in my use case I will try to write something like : `[c.patcherargs @description This doesn't work]` and ... it doesn't work :-)

**Comment by pierreguillot** [comment]
Last update should have fixed this. Tell me if it is the behavior you expected.
Cheers

**Comment by avilleret** [comment]
yes it works, thanks a lot !
