### ISSUE TITLE
missing pd.lib or should we provide pd headers and lib ?

### ISSUE THREAD

**Issue by avilleret** [CICM/CicmWrapper#11]
I noticed a while ago that CicmWrapper comes with pd's header, both vanilla and extended and also a `pd.dll` and `pd.def` but there is no `pd.lib` which is needed for building on Windows.
At least it appears on [CreamLibrary VS Project file](https://github.com/CICM/CreamLibrary/blob/master/c.library.vcxproj#L165) (despite it is deprecated).

I see here some inconstancy : if you provide headers why do you not include the associated .lib ?

BTW, my point of view is to not ship header nor lib but let the user/developer download the version he want to build against.

I'm writing that, because I'm having trouble compiling a project using CicmWrapper with MSVC.

**Comment by pierreguillot** [comment]
Hi,
I'm agree, I wanted to remove these headers since a long time and now it's done...
7eda6fb623067b7f56fd0e3b858931e5b0aafebc 
I don't have a Windows computer today so I can't try with MSVC, I'll do it tomorrow.
