### ISSUE TITLE
le message set He's avec l'objet c.prepend

### ISSUE THREAD

**Issue by MichelGoffin** [CICM/CicmWrapper#3]
Version : Pd-0.43.3 ("extended-20121002") compiled 07:56:35 Oct 2 2012
Description: Ubuntu 12.04.4 LTS
Objet : c.prepend

Le message set He's ne marche pas dans l'aide.

Message d'erreur en console
Pd: buffer space wasn't sufficient for long GUI string

**Comment by pierreguillot** [comment]
This should be solved.
