### ISSUE TITLE
can't load c.library due to undefined canvas_dspstate

### ISSUE THREAD

**Issue by avilleret** [CICM/CicmWrapper#5]
on Ubuntu 14.04 64bit with Pd 0.46-0,
I can't load c.library due to this error : 

```
./c.library.pd_linux: ./c.library.pd_linux: undefined symbol: canvas_dspstate
c.library: can't load library
```

HoaLibrary suffers from this too, see https://github.com/CICM/HoaLibrary/issues/21

`canvas_dspstate` is only defined in Pd-extended, not in Vanilla, so I think the Vanilla build should exclude all calls to this function.

**Comment by iooops** [comment]
Has it been fixed? What can I do to use csound6~ in PD on my linux machine now?

**Comment by pierreguillot** [comment]
Yes, but there is no relation with csound...
